#!/bin/bash
#
# Installs an alternate codium icon.

set -e

# constants and defined cli parameters
PROGRAM_NAME="$(basename "$0")"
readonly PROGRAM_NAME
readonly FALSE=0
readonly TRUE=1
readonly HELP_SHORT_OPT="h"
readonly HELP_LONG_OPT="help"

CODE_ICON_SVG="code-icon.svg"
LETTER_PRESS_SVG="letterpress.svg"
LETTER_PRESS_HC_SVG="letterpress-hc.svg"
LETTER_PRESS_DARK_SVG="letterpress-dark.svg"

declare -A ICONS_PATHS=(
    ["${CODE_ICON_SVG}"]="/usr/share/codium/resources/app/out/vs/workbench/browser/media/${CODE_ICON_SVG}"
    ["${LETTER_PRESS_SVG}"]="/usr/share/codium/resources/app/out/vs/workbench/browser/parts/editor/media/${LETTER_PRESS_SVG}"
    ["${LETTER_PRESS_HC_SVG}"]="/usr/share/codium/resources/app/out/vs/workbench/browser/parts/editor/media/${LETTER_PRESS_HC_SVG}"
    ["${LETTER_PRESS_DARK_SVG}"]="/usr/share/codium/resources/app/out/vs/workbench/browser/parts/editor/media/${LETTER_PRESS_DARK_SVG}"
)
readonly ICONS_PATHS

# combining all short opts to form shortopts for getopt
readonly short_opts="${HELP_SHORT_OPT}"

help_option="${FALSE}"
# do not combine long opts into their own variable
eval set -- "$(getopt --options "${short_opts}" --long "${HELP_LONG_OPT}" --name "${PROGRAM_NAME}" -- "$@")"

# determine behavior of program from cli arguments
while true; do
    case "$1" in
        "-${HELP_SHORT_OPT}" | "--${HELP_LONG_OPT}")    help_option="${TRUE}"; shift ;;
        "--")                                           shift; break ;;
        *)                                              break ;;
    esac
done

if (( help_option )); then
        cat << _EOF_
Usage: ${PROGRAM_NAME} [-${HELP_SHORT_OPT}]

Installs an alternate codium icon.

Options:
    -${HELP_SHORT_OPT}, --${HELP_LONG_OPT}      show this help message and exit

_EOF_
    exit 0
fi

ROOT_UID=0
if [ "$(id --user)" != "${ROOT_UID}" ]; then
    echo "${PROGRAM_NAME}: you must run this as root" >&2
    exit 1
fi

# Realistically, if one file cannot be found, then its probable the rest won't
# exist either.
if ! [ -f "${ICONS_PATHS[${CODE_ICON_SVG}]}" ]; then
	echo "${PROGRAM_NAME}: cannot detect default icon, is codium installed?" >&2
	exit 1
fi

for icon in "${!ICONS_PATHS[@]}"; do
    install --mode=644 "../assets/${icon}" "${ICONS_PATHS[${icon}]}"
done

exit 0
