#!/bin/bash
#
# Makes common development directories in HOME.

set -e

# constants and defined cli parameters, opt ==> option
PROGRAM_NAME="$(basename "$0")"
readonly PROGRAM_NAME
readonly HELP_SHORT_OPT="h"
readonly HELP_LONG_OPT="help"
COMMON_DIRS=(
    "git"
    "hg"
    "src"
    "svn"
)
# combining all short opts to form shortopts for getopt
readonly short_opts="${HELP_SHORT_OPT}"

help_option=false
# do not combine long opts into their own variable
eval set -- "$(getopt --options "${short_opts}" --long "${HELP_LONG_OPT}" --name "${PROGRAM_NAME}" -- "$@")"

# determine behavior of program from cli arguments,
# cli ==> command line interface
while true; do
    case "$1" in
        "-${HELP_SHORT_OPT}" | "--${HELP_LONG_OPT}")    help_option=true; shift ;;
        "--")                                           shift; break ;;
        *)                                              break ;;
    esac
done

# for reference on why just if [ ${help_option} ]; ... is a bad idea:
# https://stackoverflow.com/questions/2953646/how-can-i-declare-and-use-boolean-variables-in-a-shell-script#answer-21210966
if [ "${help_option}" = true ]; then
        cat << _EOF_
Usage: ${PROGRAM_NAME} [-${HELP_SHORT_OPT}]

Makes common development directories in HOME.

Options:
    -${HELP_SHORT_OPT}, --${HELP_LONG_OPT}      show this help message and exit

_EOF_
    exit 0
fi

for dirname in "${COMMON_DIRS[@]}"; do 
    if ! [ -d "${HOME}/${dirname}" ]; then
        mkdir --parents "${HOME}/$dirname"
    fi
done

exit 0
