#!/bin/bash
#
# Small script that prints all the files with TODO 'PATTERNS',
# along with the TODO message.

PROGRAM_NAME="$(basename "$0")"
PATTERN=

if [ -z "$GIT_REPOS_PATH" ]; then
	read -r -p "What directory are git repositories stored in? ==> " -i "$HOME" GIT_REPOS_PATH
fi

ROOT_DIR="$GIT_REPOS_PATH"

walkdirtree () {
    DIR="$1"
    # shellcheck disable=2181,2063
    # NOTE: I've seen bizarre occurances where
    # filenames have a '*' character appended to them
    # 
    # is the directory not empty?
    if [ "$(find "$DIR" | wc --lines)" -gt 1 ]; then
        for f in "$DIR"/*; do
            if [ -d "$f" ]; then
                walkdirtree "$f"
            elif grep --quiet \* <<< "$f"; then
                continue
            else 
                echo "$f"
            fi
        done
    fi
}

for f in $(walkdirtree "$ROOT_DIR"); do
    grep --initial-tab --regexp "$PATTERN" --with-filename "$f"
done

exit 0
