#!/bin/bash
#
# Small script that decapitalizes every file
# starting at the PWD.

FILES="$(find . -iname '*[[:upper:]]*')"
old_IFS=$IFS
IFS=$'\n'
for f in $FILES; do 
    lower_f=$(tr '[:upper:]' '[:lower:]' <<< "$f"); 
    cd "$(dirname "$f")" || exit 
    mv "$(basename "$f")" "$(basename "$lower_f")"; 
    cd - > /dev/null || exit
done

IFS=$old_IFS

exit 0
