pipeline {
    agent any

    stages {
        stage('Build (python)') {
            when {
                expression {
                    "${params.PROGLANG}".toLowerCase() == "python"
                }
            }
            steps {
                checkout scm
                sh 'make prefix="${PWD}" PROGLANG=python setup'
                sh 'make prefix="${PWD}" PROGLANG=python install'
            }
        }
        stage('Build (shell)') {
            when {
                expression {
                    "${params.PROGLANG}".toLowerCase() == "shell"
                }
            }
            steps {
                checkout scm
                sh 'make prefix="${PWD}" PROGLANG=shell install'
                sh 'make prefix="${PWD}" PROGLANG=shell install'
            }
        }
        stage('Run') {
            when {
                // Accessing the currentBuild.result variable allows the pipeline to determine if
                // there were any failures in the previous stages.
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS' && "${params.PIPELINE_MODE}".toLowerCase() == "run"
                }
            }
            steps {
                sh 'PATH="${PWD}/bin/:${PATH}" ./bin/${SCRIPT_NAME} ${SCRIPT_ARGS}'
            }
        }
    }

    post {
        failure {
            emailext body: 'Check console output at ${BUILD_URL} to view the results. \n\n ${CHANGES} \n\n -------------------------------------------------- \n${BUILD_LOG, maxLines=100, escapeHtml=false}',
                     to: System.getenv('JENKINS_ADMIN_EMAIL') ?: "",
                     subject: "Build failed in Jenkins: ${JOB_NAME} - #${BUILD_NUMBER}"
        }
        cleanup {
            // inspired by:
            // https://stackoverflow.com/questions/37468455/jenkins-pipeline-wipe-out-workspace#answer-46914723
            sh 'make prefix="${PWD}" uninstall'
            cleanWs()
        }
    }
}
