---
name: Build the Docker images

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "5 8 * * 0"
  push:
    branches:
      - "**"

jobs:
  gps-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: cavcrosby
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push the gps-python Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/gps-python.Dockerfile
          push: true
          tags: cavcrosby/gps-python:latest
